back to scripted tag

diff --git a/.travis.yml b/.travis.yml
--- a/.travis.yml
+++ b/.travis.yml
@@ -49,16 +49,12 @@ matrix:
 #      - git
 #      - libxml2-utils
 
-# before_install:
-#   # on osx use brew to install autotools and compiler
-#   - if [[ "$TRAVIS_OS_NAME" == "osx" ]]; then
-#       brew update ;
-#       brew install libtool ;
-#       brew install automake ;
-#       brew cask uninstall oclint ;
-#       brew install gcc49 ;
-#       brew postinstall gcc49 ;
-#     fi
+before_install:
+  # on osx use brew to install autotools and compiler
+  - if [[ "$TRAVIS_OS_NAME" == "osx" ]]; then
+       brew update ;
+       brew install hub;
+    fi
 
 # install:
 #  # install pre-built packages needed to compile freesurfer
@@ -69,9 +65,19 @@ script:
   # test doing dake build then install step via script
   travis_wait 30 ./src/build.sh
 
+# add a timestamp tage before deploy
+before_deploy:
+  - git config --local user.name "buildqa"
+  - git config --local user.email "buildqa@contbay.com"
+  # create year-month-day tag, allow to fail if already exists ( >1 build per day)
+  - hub release create -m "Travis CI build" "$(date +'%Y-%m-%d')" || true
+  # upload assets to existing tar
+  # - bash -x ./upload-github-release-asset.sh owner=buildqa repo=tester1 github_api_token=$GITHUB_TOKEN filename=./install/darwin.tgz tag="$(date +'%Y-%m-%d')"
+
 deploy:
   provider: releases
   api_key: $GITHUB_TOKEN
+  overwrite: true
   file: "./install/darwin.tgz"
   skip_cleanup: true
 
